import 'dart:math';

import '../../models/difficulty.dart';
import '../../models/hint.dart';
import '../../models/sudoku_grid.dart';
import '../../models/sudoku_puzzle.dart';
import 'bitset/bitset_solver.dart';
import 'board_generator.dart';
import 'clue_remover.dart';
import 'difficulty_evaluator.dart';

/// Orchestrates board generation end to end — the "Generator" module.
///
/// [Difficulty.beginner]/[Difficulty.easy] are generated by given count (see
/// [_generateByGivenCount]): [ClueRemover] digs straight to the tier's
/// [Difficulty.givenCount] preserving only uniqueness — and in
/// 180°-rotational pairs, so these easiest tiers carry a point-symmetric
/// givens pattern (the harder tiers stay asymmetric, prioritising difficulty
/// and sparseness). The dig itself isn't difficulty-gated, so the board is
/// re-evaluated afterward and regenerated until its tier matches the bucket
/// (best-effort, with a fallback so generation never fails).
///
/// [Difficulty.medium] and up use HoDoKu's generator loop, ported from
/// ref/release2.2.0 (`BackgroundGenerator.generate` +
/// `SudokuGenerator.generateInitPos`), in [_generateByTechnique]: the dig is
/// BLIND — every cell is tried once in random order and kept out only if
/// uniqueness survives, so the board comes out minimal and difficulty never
/// steers the dig. The candidate is then solved exactly ONCE by the
/// [BitsetSolver] — the app's single difficulty authority, HoDoKu-style —
/// aborting early the moment it exceeds the target tier (`maxDifficulty`),
/// and accepted only on an exact match: the
/// [DifficultyEvaluator] combined tier must equal the target AND the score
/// band alone must too (HoDoKu's `rejectTooLowScore` — a puzzle whose
/// hardest step reaches the tier but whose total work sits in a lower band
/// plays too easy for its label). Any miss discards the whole board and
/// retries with a fresh grid; with rejection made cheap by the early abort,
/// many fast tries replace the old ceiling-gated dig that ran a human solve
/// per removed clue.
class SudokuGenerator {
  SudokuGenerator({
    Random? random,
    BoardGenerator? boardGenerator,
    ClueRemover? clueRemover,
    BitsetSolver? solver,
    DifficultyEvaluator? difficultyEvaluator,
  })  : _boardGenerator = boardGenerator ?? BoardGenerator(random: random),
        _clueRemover = clueRemover ?? ClueRemover(random: random),
        _solver = solver ?? BitsetSolver(),
        _evaluator = difficultyEvaluator ?? DifficultyEvaluator();

  /// HoDoKu's background-generation retry budget
  /// (`BackgroundGenerator.MAX_TRIES`). Attempts are cheap now (one blind
  /// dig + one early-aborted solve), so the budget is sized to make the
  /// StateError below effectively unreachable rather than to bound work —
  /// typical tiers accept within tens of attempts.
  static const _maxAttempts = 20000;

  /// Blind-dig target: the proven mathematical floor for a uniquely
  /// solvable 9x9 (HoDoKu's `maxPosToFill`). Never actually reached — the
  /// dig stops wherever uniqueness pruning leaves it (~22-27 givens) — it
  /// just means "dig as deep as uniqueness allows".
  static const _digFloor = 17;

  /// Retry budget for the given-count tiers' re-evaluation loop (see
  /// [_generateByGivenCount]). Each attempt is a fast dig + human solve, so a
  /// generous cap is cheap; the loop returns early the moment a board's
  /// evaluated tier matches, and falls back to the first attempt otherwise.
  static const _givenCountMaxAttempts = 60;

  /// Expert puzzles are pushed toward a sparser board (require.md #5 asked
  /// for a givens cap). Measured: uniqueness-minimal expert boards land at
  /// ~24 givens on average, so the originally-requested "< 22" was only
  /// reachable ~8% of the time (very slow to force). 23 sits just below the
  /// median — it reliably trims the fuller 24-26 boards without exploding
  /// generation time. Enforced as an acceptance condition with a fallback,
  /// so it can never become a hard failure (see [_generateByTechnique]).
  static const _expertMaxGivens = 23;

  // Bronze/Silver are the only given-count tiers: their bands (singles /
  // hidden-single + intersections) don't separate cleanly by technique, so
  // digging to a target given-count and stopping is both faster (one pass,
  // always succeeds) and a truer knob for them. Every tier from Gold up is
  // technique-gated.
  static const _givenCountBasedTiers = {
    Difficulty.beginner,
    Difficulty.easy,
  };

  final BoardGenerator _boardGenerator;
  final ClueRemover _clueRemover;
  final BitsetSolver _solver;
  final DifficultyEvaluator _evaluator;

  SudokuPuzzle generate(Difficulty difficulty) =>
      _givenCountBasedTiers.contains(difficulty)
          ? _generateByGivenCount(difficulty)
          : _generateByTechnique(difficulty);

  /// Digs symmetrically to [Difficulty.givenCount] preserving only
  /// uniqueness (no difficulty ceiling during the dig — see class doc), then
  /// re-evaluates and regenerates until the board's tier matches the bucket.
  /// The dig can otherwise land a rung off (usually too easy: solvable by
  /// fewer techniques than the tier implies), so this tightening keeps the
  /// label honest; the first attempt is kept as a fallback so it never fails.
  SudokuPuzzle _generateByGivenCount(Difficulty difficulty) {
    SudokuPuzzle? fallback;
    for (var attempt = 1; attempt <= _givenCountMaxAttempts; attempt++) {
      final solvedBoard = _boardGenerator.generateSolvedBoard();
      final dug = _clueRemover.removeClues(
        solvedBoard,
        difficulty.givenCount,
        symmetric: true,
      );
      final puzzle = _toPuzzle(dug, solvedBoard, difficulty);
      if (_evaluator
              .evaluate(_solver.solve(dug).toSolveResult())
              .highestDifficulty ==
          difficulty) {
        return puzzle;
      }
      fallback ??= puzzle;
    }
    return fallback!;
  }

  SudokuPuzzle _generateByTechnique(Difficulty difficulty) {
    // Expert only: a tier-correct candidate that missed the givens cap is
    // kept as a last resort, so exhausting every attempt degrades to a
    // slightly-too-full expert puzzle instead of a StateError — which the
    // puzzle queue would swallow and, on the take() miss fallback, would
    // mean a very long synchronous generate on the UI thread.
    SudokuPuzzle? overfullFallback;

    for (var attempt = 1; attempt <= _maxAttempts; attempt++) {
      final solvedBoard = _boardGenerator.generateSolvedBoard();

      // Blind dig: uniqueness is the only gate, so this lands minimal
      // (every cell was tried once) without a single human solve.
      final dug = _clueRemover.removeClues(solvedBoard, _digFloor);

      // One bitset solve per candidate, early-aborted the moment the board
      // proves harder than the target — an abort comes back `solved: false`
      // and is rejected below exactly like a stuck board.
      final result = _solver.solve(dug, maxDifficulty: difficulty);
      if (!result.solved) continue;

      final evaluated = _evaluator.evaluate(result.toSolveResult());
      if (evaluated.highestDifficulty != difficulty ||
          scoreBand(evaluated.score) != difficulty) {
        // Undershoot, or a score band below the tier its hardest step
        // reached (HoDoKu's rejectTooLowScore) — retry with a fresh board.
        continue;
      }

      final givens = dug.fold<int>(
          0, (sum, row) => sum + row.where((v) => v != 0).length);
      if (difficulty != Difficulty.expert || givens <= _expertMaxGivens) {
        return _toPuzzle(dug, solvedBoard, difficulty);
      }
      overfullFallback ??= _toPuzzle(dug, solvedBoard, difficulty);
    }

    final fallback = overfullFallback;
    if (fallback != null) return fallback;

    throw StateError(
      'SudokuGenerator: could not produce a $difficulty puzzle that exactly '
      'matches the target difficulty after $_maxAttempts attempts.',
    );
  }

  SudokuPuzzle _toPuzzle(
    List<List<int>> puzzle,
    List<List<int>> solution,
    Difficulty difficulty,
  ) =>
      SudokuPuzzle(
        puzzle: SudokuGrid(puzzle),
        solution: SudokuGrid(solution),
        fixedMask: List.generate(
          9,
          (r) => List.generate(9, (c) => puzzle[r][c] != 0),
        ),
        difficulty: difficulty,
      );
}
